### ISSUE TITLE
Open Docs and vite in different ports

### ISSUE THREAD

**Issue by lucbpz** [lucbpz/react-virtual-select#15]
When I start both of them in a console, they both open in `localhost:3000`.

I want to have them in different ports by default and that means changing for example de docusaurus port to another one different than 3000.

**Comment by elangbayu** [comment]
> _**I want to have them always in the same port**_, and that means changing for example de docusaurus port to **_another one different_** than 3000.

I'm sorry but i don't get it. So do you want to keep both of docusarus and vite run on the same port? Or do you want them to run on different port?

**Comment by lucbpz** [comment]
> > _**I want to have them always in the same port**_, and that means changing for example de docusaurus port to **_another one different_** than 3000.
> 
> I'm sorry but i don't get it. So do you want to keep both of docusarus and vite run on the same port? Or do you want them to run on different port?

Sorry I didn’t explain myself. Different ports of course! 😅

**Comment by elangbayu** [comment]
😀 Okay, thanks for the clarity, I have opened the pull request #16 , thank you for the review as this is my first contribution to public repo 🙏🏽
